package engine.script;

import engine.text.Locale;
import engine.text.Localizable;

public final class ScriptRunner {
    public record ExecutionReport(Object returnedValue, ExecutionContext executionContext) {}

    /**
     * Executes the given script and return the value generated by the last executed.
     */
    public static ExecutionReport execute(final Localizable<Type> declaredKoanClass, final Locale locale, final Expression[] script) {
        Object lastCallValue = null;
        final var ctx = new ExecutionContext(declaredKoanClass, locale);

        for(final var stmt: script) {
            lastCallValue = stmt.execute(ctx);
        }
        
        return new ExecutionReport(lastCallValue, ctx);
    }
}
